theme: jekyll-theme-minimal
show_downloads: true
title: thermal-events
description: Python library that handles the thermal events and the interaction with the thermal events database of fusion reactors
github:
  zip_url: https://github.com/IRFM/thermal-events/zipball/main
  tar_url: https://github.com/IRFM/thermal-events/tarball/main